package com.njjd.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.njjd.domain.QuestionEntity;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "QUESTION_ENTITY".
*/
public class QuestionEntityDao extends AbstractDao<QuestionEntity, String> {

    public static final String TABLENAME = "QUESTION_ENTITY";

    /**
     * Properties of entity QuestionEntity.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property QuestionId = new Property(0, String.class, "questionId", true, "QUESTION_ID");
        public final static Property Title = new Property(1, String.class, "title", false, "TITLE");
        public final static Property Content = new Property(2, String.class, "content", false, "CONTENT");
        public final static Property Photo = new Property(3, String.class, "photo", false, "PHOTO");
        public final static Property Pic = new Property(4, String.class, "pic", false, "PIC");
        public final static Property Uids = new Property(5, String.class, "uids", false, "UIDS");
        public final static Property FocusNum = new Property(6, String.class, "focusNum", false, "FOCUS_NUM");
        public final static Property AnswerNum = new Property(7, String.class, "answerNum", false, "ANSWER_NUM");
        public final static Property IsFocus = new Property(8, int.class, "isFocus", false, "IS_FOCUS");
        public final static Property DateTime = new Property(9, String.class, "dateTime", false, "DATE_TIME");
        public final static Property Tag = new Property(10, String.class, "tag", false, "TAG");
        public final static Property Kind = new Property(11, String.class, "kind", false, "KIND");
        public final static Property Tag_id = new Property(12, String.class, "tag_id", false, "TAG_ID");
        public final static Property Part_num = new Property(13, String.class, "part_num", false, "PART_NUM");
        public final static Property IsVisiable = new Property(14, String.class, "isVisiable", false, "IS_VISIABLE");
    }


    public QuestionEntityDao(DaoConfig config) {
        super(config);
    }
    
    public QuestionEntityDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"QUESTION_ENTITY\" (" + //
                "\"QUESTION_ID\" TEXT PRIMARY KEY NOT NULL ," + // 0: questionId
                "\"TITLE\" TEXT," + // 1: title
                "\"CONTENT\" TEXT," + // 2: content
                "\"PHOTO\" TEXT," + // 3: photo
                "\"PIC\" TEXT," + // 4: pic
                "\"UIDS\" TEXT," + // 5: uids
                "\"FOCUS_NUM\" TEXT," + // 6: focusNum
                "\"ANSWER_NUM\" TEXT," + // 7: answerNum
                "\"IS_FOCUS\" INTEGER NOT NULL ," + // 8: isFocus
                "\"DATE_TIME\" TEXT," + // 9: dateTime
                "\"TAG\" TEXT," + // 10: tag
                "\"KIND\" TEXT," + // 11: kind
                "\"TAG_ID\" TEXT," + // 12: tag_id
                "\"PART_NUM\" TEXT," + // 13: part_num
                "\"IS_VISIABLE\" TEXT);"); // 14: isVisiable
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"QUESTION_ENTITY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, QuestionEntity entity) {
        stmt.clearBindings();
 
        String questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindString(1, questionId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(4, photo);
        }
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(5, pic);
        }
 
        String uids = entity.getUids();
        if (uids != null) {
            stmt.bindString(6, uids);
        }
 
        String focusNum = entity.getFocusNum();
        if (focusNum != null) {
            stmt.bindString(7, focusNum);
        }
 
        String answerNum = entity.getAnswerNum();
        if (answerNum != null) {
            stmt.bindString(8, answerNum);
        }
        stmt.bindLong(9, entity.getIsFocus());
 
        String dateTime = entity.getDateTime();
        if (dateTime != null) {
            stmt.bindString(10, dateTime);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(11, tag);
        }
 
        String kind = entity.getKind();
        if (kind != null) {
            stmt.bindString(12, kind);
        }
 
        String tag_id = entity.getTag_id();
        if (tag_id != null) {
            stmt.bindString(13, tag_id);
        }
 
        String part_num = entity.getPart_num();
        if (part_num != null) {
            stmt.bindString(14, part_num);
        }
 
        String isVisiable = entity.getIsVisiable();
        if (isVisiable != null) {
            stmt.bindString(15, isVisiable);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, QuestionEntity entity) {
        stmt.clearBindings();
 
        String questionId = entity.getQuestionId();
        if (questionId != null) {
            stmt.bindString(1, questionId);
        }
 
        String title = entity.getTitle();
        if (title != null) {
            stmt.bindString(2, title);
        }
 
        String content = entity.getContent();
        if (content != null) {
            stmt.bindString(3, content);
        }
 
        String photo = entity.getPhoto();
        if (photo != null) {
            stmt.bindString(4, photo);
        }
 
        String pic = entity.getPic();
        if (pic != null) {
            stmt.bindString(5, pic);
        }
 
        String uids = entity.getUids();
        if (uids != null) {
            stmt.bindString(6, uids);
        }
 
        String focusNum = entity.getFocusNum();
        if (focusNum != null) {
            stmt.bindString(7, focusNum);
        }
 
        String answerNum = entity.getAnswerNum();
        if (answerNum != null) {
            stmt.bindString(8, answerNum);
        }
        stmt.bindLong(9, entity.getIsFocus());
 
        String dateTime = entity.getDateTime();
        if (dateTime != null) {
            stmt.bindString(10, dateTime);
        }
 
        String tag = entity.getTag();
        if (tag != null) {
            stmt.bindString(11, tag);
        }
 
        String kind = entity.getKind();
        if (kind != null) {
            stmt.bindString(12, kind);
        }
 
        String tag_id = entity.getTag_id();
        if (tag_id != null) {
            stmt.bindString(13, tag_id);
        }
 
        String part_num = entity.getPart_num();
        if (part_num != null) {
            stmt.bindString(14, part_num);
        }
 
        String isVisiable = entity.getIsVisiable();
        if (isVisiable != null) {
            stmt.bindString(15, isVisiable);
        }
    }

    @Override
    public String readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0);
    }    

    @Override
    public QuestionEntity readEntity(Cursor cursor, int offset) {
        QuestionEntity entity = new QuestionEntity( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // questionId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // title
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // content
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // photo
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // pic
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // uids
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // focusNum
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // answerNum
            cursor.getInt(offset + 8), // isFocus
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // dateTime
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // tag
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // kind
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // tag_id
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // part_num
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14) // isVisiable
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, QuestionEntity entity, int offset) {
        entity.setQuestionId(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setTitle(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setContent(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setPhoto(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setPic(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setUids(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setFocusNum(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setAnswerNum(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setIsFocus(cursor.getInt(offset + 8));
        entity.setDateTime(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setTag(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setKind(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setTag_id(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setPart_num(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setIsVisiable(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
     }
    
    @Override
    protected final String updateKeyAfterInsert(QuestionEntity entity, long rowId) {
        return entity.getQuestionId();
    }
    
    @Override
    public String getKey(QuestionEntity entity) {
        if(entity != null) {
            return entity.getQuestionId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(QuestionEntity entity) {
        return entity.getQuestionId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
